sections:
  main:
    display: Main
    fields:
      -
        handle: site_name
        field:
          input_type: text
          antlers: false
          display: 'Site Name'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - required
      -
        handle: social_media_profiles
        field:
          fields:
            -
              handle: social_media_icon
              field:
                mode: list
                container: assets
                folder: socialicons
                restrict: false
                allow_uploads: true
                show_filename: true
                max_files: 1
                display: 'Social Media Icon'
                type: assets
                icon: assets
                width: 25
                listable: hidden
                instructions_position: above
                visibility: visible
                validate:
                  - required
            -
              handle: social_media_display_name
              field:
                input_type: text
                antlers: false
                display: 'Display Name'
                type: text
                icon: text
                width: 25
                listable: hidden
                instructions_position: above
                visibility: visible
                validate:
                  - required
            -
              handle: social_media_profile_url
              field:
                input_type: text
                antlers: false
                display: 'Profile URL'
                type: text
                icon: text
                width: 50
                listable: hidden
                instructions_position: above
                visibility: visible
                validate:
                  - required
                  - url
          mode: table
          reorderable: true
          display: 'Social Media Profiles'
          type: grid
          icon: grid
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: author_blurb
        field:
          antlers: false
          display: 'Author Blurb'
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - 'max:120'
